### ISSUE TITLE
Runtime problems

### ISSUE THREAD

**Issue by Wnnn-S** [bbaranoff/openlte#2]
When I use bladerf for LTE redirection, it is displayed in shell2 as follows:

telnet localhost 30000

Trying 127.0.0.1...

Connected to localhost.

Escape character is '^]'.

*** LTE FDD ENB ***

Type help to see a list of commands

rx_ gain 30

fail "invalid command"

write rx_ gain 30

ok

write tx_ gain 80

ok

write mcc 460

ok

write mnc 00

ok

write band 40

ok

write dl_ earfcn 38950

ok

start

fail "cant start"

Displayed in shell1:

LTE_ fdd_ enodeb

*** LTE FDD ENB ***

Please connect to control port 30000

[INFO] [UHD] linux; GNU C++ version 9.3.0; Boost_ 107100; UHD_ 3.15.0. HEAD-0-gdbaf4132

[INFO @ host/libraries/libbladeRF/src/helpers/version.c:79] Firmware version (v2.4.0) is newer than entries in libbladeRF's compatibility table. Please update libbladeRF if problems arise.

[INFO @ host/libraries/libbladeRF/src/helpers/version.c:103] FPGA version (v0.14.0) is newer than entries in libbladeRF's compatibility table. Please update libbladeRF if problems arise.

I wonder if it's the bladerf problem? The bladerf version is as follows:

bladeRF> version

bladeRF-cli version: 1.8.0-git-f03d8433

libbladeRF version: 2.2.1-git-f03d8433

Firmware version: 2.4.0-git-a3d5c55f

FPGA version: 0.14.0 (configured from SPI flash)

**Comment by bbaranoff** [comment]
May try
wget https://www.nuand.com/fx3/bladeRF_fw_v2.3.2.img
bladeRF-cli -f bladeRF_fw_v2.3.2.img
wget https://www.nuand.com/fpga/v0.8.0/hostedxA4.rbf (or xA9 x40 x115 ?)
bladeRF-cli -l hostedxA4.rbf

**Comment by Wnnn-S** [comment]
I followed your settings, but it still shows

start

fail "cant start"

And in shell1, the bladerf does start because the bladerf indicator flashes several times. However, there is no such content as setting the sampling rate and setting the frequency.

**Comment by bbaranoff** [comment]
Try with sudo LTE_fdd_enodeB ??

**Comment by Wnnn-S** [comment]
Using sudo will display segmentation fault :). Segmentation fault also occurs in gnuradio-companion , LTE_fdd_dl_scan  and other LTE instructions, it seems to be a GNU problem?

**Comment by bbaranoff** [comment]
https://github.com/bbaranoff/openLTE2GSM
Try this ?? Lol
edit : can I close ?
edit2 : I suppose  I can close

**Comment by Wnnn-S** [comment]
Sorry I'm late! I tried to install DEB and successfully run it after installing some missing dependencies. Thank you very much!

**Comment by bbaranoff** [comment]
Updated with missing dependencies on ubuntu 20.04
